#!/bin/bash
# Run the specified application, with any arguments, in the
# 64-bit Debian container, using the host OS' X-server and pulseaudio
# server. Also include a QT fixup for apps like vlc that need it.
#
# Copyright (c) 2019 sakaki <sakaki@deciban.com>
# License: GPL 3.0+
# NO WARRANTY

if ! ds64-running; then
        zenity --error --no-wrap \
  --title="Error starting 64-bit program" \
  --text="The debian-stretch-64 container is not running!\nPlease start it and try again." \
  --timeout=5
        exit 1
fi
sudo systemd-run \
	--setenv=QT_AUTO_SCREEN_SCALE_FACTOR=0 \
	--setenv=DISPLAY="${DISPLAY}" \
	--setenv=PULSE_SERVER="unix:/run/host-user/1000/pulse/native" \
	--machine=debian-stretch-64 \
	--uid=1000 --gid=1000 \
	"${@}"
