#!/bin/bash
# Start up the debian-stretch-64 container, if not already running.
#
# Copyright (c) 2019 sakaki <sakaki@deciban.com>
# License: GPL 3.0+
# NO WARRANTY

if ds64-running; then
        zenity --info --no-wrap \
  --title="Nothing to do" \
  --text="The debian-stretch-64 container is already running." \
  --timeout=5
        exit 0
fi
sudo machinectl start debian-stretch-64
RUNNING=0
for ((i=0;i<10;i++)); do
	if ds64-running; then
		RUNNING=1
		break
	fi
	sleep 1
done
if ((RUNNING==1)); then
        zenity --info --no-wrap \
  --title="Success" \
  --text="The debian-stretch-64 container is now running." \
  --timeout=5
        exit 0
else
	zenity --error --no-wrap \
  --title="Error" \
  --text="Failed to start the debian-stretch-64 container!" \
  --timeout=5
        exit 1
fi

