#!/bin/bash
# Stop the debian-stretch-64 container, if running.
#
# Copyright (c) 2019 sakaki <sakaki@deciban.com>
# License: GPL 3.0+
# NO WARRANTY

if ! ds64-running; then
        zenity --info --no-wrap \
  --title="Nothing to do" \
  --text="The debian-stretch-64 container is already stopped." \
  --timeout=5
        exit 0
fi
sudo machinectl stop debian-stretch-64
RUNNING=1
for ((i=0;i<10;i++)); do
        if ! ds64-running; then
                RUNNING=0
                break
        fi
	sleep 1
done
if ((RUNNING==0)); then
        zenity --info --no-wrap \
  --title="Success" \
  --text="The debian-stretch-64 container is now stopped." \
  --timeout=5
        exit 0
else
	zenity --error --no-wrap \
  --title="Error" \
  --text="Failed to stop the debian-stretch-64 container!" \
  --timeout=5
        exit 1
fi

