.TH DS64\-START 1 "FEBRUARY 2020"
.SH NAME
.PP
ds64\-start \- start the 64\-bit Debian sidekick OS, if not running
.SH SYNOPSIS
.PP
\fB\fCds64\-start\fR
.SH DESCRIPTION
.PP
\fB\fCds64\-start\fR attempts to boot up the current 64\-bit Debian 'sidekick' guest
OS, if it is not already running.
.PP
Upon a error\-free return from this command, you can rely upon the guest OS
being available, allowing you to e.g.,
invoke applications within it using 
.BR ds64-runner (1).
.PP
To shut down the guest again, use 
.BR ds64-stop (1).
.PP
A 
.BR zenity (1) 
dialog status display is provided on exit, with a 5 second
auto\-dismissal timeout, where possible.
.SH EXIT STATUS
.PP
The exit status is 0 if the guest OS is running upon exit, and 1 otherwise.
.SH FILES
.PP
\fI/etc/ds64.conf\fP
.PP
Configuration file specifying various controlling environment
variables, including \fB\fC$DS64_NAME\fR (defaults to \fIdebian\-buster\-64\fP) and
\fB\fC$DS64_DIR\fR (defaults to \fI/var/lib/machines/debian\-buster\-64\fP).
.SH BUGS
.PP
Bugs should be reported on the
project's GitHub page \[la]https://github.com/sakaki-/raspbian-nspawn-64/issues\[ra]\&.
.SH COPYRIGHT
.PP
Copyright \[co] 2019\-20 sakaki
.PP
License GPLv3+ GNU GPL version 3 or later \[la]http://gnu.org/licenses/gpl.html\[ra]
.PP
This is free software, you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH AUTHORS
.PP
sakaki \[la]sakaki@deciban.com\[ra]
.SH SEE ALSO
.PP
.BR ds64-runner (1), 
.BR ds64-stop (1), 
.BR zenity (1)
